ALTER TABLE "shops" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "admin_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "files" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "order_options" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "status_history" ENABLE ROW LEVEL SECURITY;
